// Code generated by rust-sdk-generator. DO NOT EDIT.

#![allow(clippy::all)]

/// Query parameters for the EstimateFeesQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct EstimateFeesQuery {
    #[serde(rename = "network")]
    pub network: String,
}

/// Call Function
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CallFunctionRequest {
    #[serde(rename = "contract")]
    pub contract: String,
    #[serde(rename = "abi")]
    pub abi: serde_json::Value,
    #[serde(rename = "calldata", default, skip_serializing_if = "Option::is_none")]
    pub calldata: Option<serde_json::Value>,
}

/// Get Canton Validator
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetCantonValidatorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "orgId")]
    pub org_id: String,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "partyHint")]
    pub party_hint: String,
}

/// Update Canton Validator
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UpdateCantonValidatorRequest {
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "validator", default, skip_serializing_if = "Option::is_none")]
    pub validator: Option<serde_json::Value>,
    #[serde(rename = "ledger", default, skip_serializing_if = "Option::is_none")]
    pub ledger: Option<serde_json::Value>,
}

/// Update Canton Validator
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UpdateCantonValidatorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "orgId")]
    pub org_id: String,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "partyHint")]
    pub party_hint: String,
}

/// Delete Canton Validator
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeleteCantonValidatorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "orgId")]
    pub org_id: String,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "partyHint")]
    pub party_hint: String,
}

/// List Canton Validators
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListCantonValidatorsResponse {
    #[serde(rename = "items")]
    pub items: Vec<crate::types::CantonValidator>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListCantonValidatorsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListCantonValidatorsQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
}

/// Request body for the createCantonValidator operation.
pub type CreateCantonValidatorRequest = serde_json::Value;

/// Create Canton Validator
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CreateCantonValidatorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "orgId")]
    pub org_id: String,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(rename = "partyHint")]
    pub party_hint: String,
}
