// Code generated by rust-sdk-generator. DO NOT EDIT.

#![allow(clippy::all)]

/// List Payouts
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayoutsResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListPayoutsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayoutsQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
    #[serde(rename = "walletId", default, skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<String>>,
    #[serde(rename = "provider", default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<Vec<String>>,
}

/// Request body for the createPayout operation.
pub type CreatePayoutRequest = serde_json::Value;

/// Request body for the requestPayoutQuote operation.
pub type RequestPayoutQuoteRequest = serde_json::Value;

/// Request Payout Quote
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RequestPayoutQuoteResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "asset")]
    pub asset: serde_json::Value,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "quotes")]
    pub quotes: Vec<serde_json::Value>,
}

/// Request body for the createPayoutAction operation.
pub type CreatePayoutActionRequest = serde_json::Value;

/// Create Payout Action
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CreatePayoutActionResponse {}
