// Code generated by rust-sdk-generator. DO NOT EDIT.

#![allow(clippy::all)]

/// List Payins
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinsResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListPayinsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinsQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
    #[serde(rename = "walletId", default, skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<String>>,
    #[serde(rename = "provider", default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<Vec<String>>,
}

/// Request body for the createPayin operation.
pub type CreatePayinRequest = serde_json::Value;

/// Get Payin Recipient
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPayinRecipientResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "recipientAddressId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_address_id: Option<String>,
}

/// Query parameters for the GetPayinRecipientQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPayinRecipientQuery {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
}

/// Request body for the registerPayinRecipient operation.
pub type RegisterPayinRecipientRequest = serde_json::Value;

/// Register Payin Recipient
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RegisterPayinRecipientResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "recipientAddressId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_address_id: Option<String>,
}

/// List Payin Balances
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinBalancesResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
}

/// Query parameters for the ListPayinBalancesQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinBalancesQuery {
    #[serde(rename = "provider")]
    pub provider: String,
}
