// Code generated by rust-sdk-generator. DO NOT EDIT.

#![allow(clippy::all)]

/// List Payins
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinsResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListPayinsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinsQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
    #[serde(rename = "walletId", default, skip_serializing_if = "Option::is_none")]
    pub wallet_id: Option<String>,
    #[serde(rename = "status", default, skip_serializing_if = "Option::is_none")]
    pub status: Option<Vec<String>>,
    #[serde(rename = "provider", default, skip_serializing_if = "Option::is_none")]
    pub provider: Option<Vec<String>>,
}

/// Request body for the createPayin operation.
pub type CreatePayinRequest = serde_json::Value;

/// Request body for the requestPayinQuote operation.
pub type RequestPayinQuoteRequest = serde_json::Value;

/// Request Payin Quote
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RequestPayinQuoteResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "tid")]
    pub tid: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "quotes")]
    pub quotes: Vec<serde_json::Value>,
}

/// Get Payin Recipient
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPayinRecipientResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "recipientAddressId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_address_id: Option<String>,
}

/// Query parameters for the GetPayinRecipientQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetPayinRecipientQuery {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
}

/// Request body for the registerPayinRecipient operation.
pub type RegisterPayinRecipientRequest = serde_json::Value;

/// Register Payin Recipient
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RegisterPayinRecipientResponse {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(
        rename = "recipientAddressId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub recipient_address_id: Option<String>,
}

/// List Payin Accounts
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinAccountsResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
}

/// Query parameters for the ListPayinAccountsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinAccountsQuery {
    #[serde(rename = "provider")]
    pub provider: String,
}

/// List Payin Balances
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinBalancesResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
}

/// Query parameters for the ListPayinBalancesQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinBalancesQuery {
    #[serde(rename = "provider")]
    pub provider: String,
}

/// List Payin Options
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinOptionsResponse {
    #[serde(rename = "assets")]
    pub assets: Vec<String>,
    #[serde(rename = "currencies")]
    pub currencies: Vec<serde_json::Value>,
}

/// Query parameters for the ListPayinOptionsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListPayinOptionsQuery {
    #[serde(rename = "provider")]
    pub provider: String,
}

/// Request body for the registerPayinAccountAsset operation.
pub type RegisterPayinAccountAssetRequest = serde_json::Value;

/// Register Payin Account Asset
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct RegisterPayinAccountAssetResponse {
    #[serde(rename = "accountId")]
    pub account_id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "assets")]
    pub assets: Vec<serde_json::Value>,
}
