// Code generated by rust-sdk-generator. DO NOT EDIT.

#[allow(unused_imports)]
use super::types::*;

/// Delegated client for fee_sponsors operations. Signed operations are split into
/// init/complete pairs so the challenge can be signed on the user side.
#[derive(Clone)]
pub struct DelegatedFeeSponsorsClient {
    client: crate::client::Client,
}

impl DelegatedFeeSponsorsClient {
    pub fn new(client: crate::client::Client) -> Self {
        DelegatedFeeSponsorsClient { client }
    }

    /// Retrieves all Fee Sponsors configured in your organization.
    pub async fn list_fee_sponsors(
        &self,
        query: Option<ListFeeSponsorsQuery>,
    ) -> Result<ListFeeSponsorsResponse, crate::error::Error> {
        let mut path = String::from("/fee-sponsors");
        if let Some(query) = &query {
            let mut q: Vec<String> = Vec::new();
            if let Some(v) = &query.limit {
                q.push(format!("limit={}", urlencoding::encode(&v.to_string())));
            }
            if let Some(v) = &query.pagination_token {
                q.push(format!(
                    "paginationToken={}",
                    urlencoding::encode(&v.to_string())
                ));
            }
            if !q.is_empty() {
                path.push('?');
                path.push_str(&q.join("&"));
            }
        }
        self.client
            .request::<ListFeeSponsorsResponse>(reqwest::Method::GET, &path, None, false)
            .await
    }

    /// Starts delegated signing for createFeeSponsor: returns the challenge to sign.
    /// Pass the signed assertion to create_fee_sponsor_complete with the same arguments.
    pub async fn create_fee_sponsor_init(
        &self,
        body: CreateFeeSponsorRequest,
    ) -> Result<crate::signer::UserActionChallenge, crate::error::Error> {
        let path = String::from("/fee-sponsors");
        let body = serde_json::to_value(&body)?;
        self.client
            .create_user_action_challenge(reqwest::Method::POST, &path, Some(&body))
            .await
    }

    /// Finishes delegated signing for createFeeSponsor: submits the signed challenge
    /// and issues the request.
    pub async fn create_fee_sponsor_complete(
        &self,
        body: CreateFeeSponsorRequest,
        challenge_identifier: String,
        assertion: crate::signer::CredentialAssertion,
    ) -> Result<CreateFeeSponsorResponse, crate::error::Error> {
        let path = String::from("/fee-sponsors");
        let body = serde_json::to_value(&body)?;
        let user_action = self
            .client
            .complete_user_action_signing(challenge_identifier, &assertion)
            .await?;
        self.client
            .request_with_user_action::<CreateFeeSponsorResponse>(
                reqwest::Method::POST,
                &path,
                Some(&body),
                &user_action,
            )
            .await
    }

    /// Retrieve a Fee Sponsor information by ID.
    pub async fn get_fee_sponsor(
        &self,
        fee_sponsor_id: String,
    ) -> Result<GetFeeSponsorResponse, crate::error::Error> {
        let path = format!("/fee-sponsors/{}", urlencoding::encode(&fee_sponsor_id));
        self.client
            .request::<GetFeeSponsorResponse>(reqwest::Method::GET, &path, None, false)
            .await
    }

    /// Starts delegated signing for deleteFeeSponsor: returns the challenge to sign.
    /// Pass the signed assertion to delete_fee_sponsor_complete with the same arguments.
    pub async fn delete_fee_sponsor_init(
        &self,
        fee_sponsor_id: String,
    ) -> Result<crate::signer::UserActionChallenge, crate::error::Error> {
        let path = format!("/fee-sponsors/{}", urlencoding::encode(&fee_sponsor_id));
        self.client
            .create_user_action_challenge(reqwest::Method::DELETE, &path, None)
            .await
    }

    /// Finishes delegated signing for deleteFeeSponsor: submits the signed challenge
    /// and issues the request.
    pub async fn delete_fee_sponsor_complete(
        &self,
        fee_sponsor_id: String,
        challenge_identifier: String,
        assertion: crate::signer::CredentialAssertion,
    ) -> Result<DeleteFeeSponsorResponse, crate::error::Error> {
        let path = format!("/fee-sponsors/{}", urlencoding::encode(&fee_sponsor_id));
        let user_action = self
            .client
            .complete_user_action_signing(challenge_identifier, &assertion)
            .await?;
        self.client
            .request_with_user_action::<DeleteFeeSponsorResponse>(
                reqwest::Method::DELETE,
                &path,
                None,
                &user_action,
            )
            .await
    }

    /// Starts delegated signing for deactivateFeeSponsor: returns the challenge to sign.
    /// Pass the signed assertion to deactivate_fee_sponsor_complete with the same arguments.
    pub async fn deactivate_fee_sponsor_init(
        &self,
        fee_sponsor_id: String,
    ) -> Result<crate::signer::UserActionChallenge, crate::error::Error> {
        let path = format!(
            "/fee-sponsors/{}/deactivate",
            urlencoding::encode(&fee_sponsor_id)
        );
        self.client
            .create_user_action_challenge(reqwest::Method::PUT, &path, None)
            .await
    }

    /// Finishes delegated signing for deactivateFeeSponsor: submits the signed challenge
    /// and issues the request.
    pub async fn deactivate_fee_sponsor_complete(
        &self,
        fee_sponsor_id: String,
        challenge_identifier: String,
        assertion: crate::signer::CredentialAssertion,
    ) -> Result<DeactivateFeeSponsorResponse, crate::error::Error> {
        let path = format!(
            "/fee-sponsors/{}/deactivate",
            urlencoding::encode(&fee_sponsor_id)
        );
        let user_action = self
            .client
            .complete_user_action_signing(challenge_identifier, &assertion)
            .await?;
        self.client
            .request_with_user_action::<DeactivateFeeSponsorResponse>(
                reqwest::Method::PUT,
                &path,
                None,
                &user_action,
            )
            .await
    }

    /// Starts delegated signing for activateFeeSponsor: returns the challenge to sign.
    /// Pass the signed assertion to activate_fee_sponsor_complete with the same arguments.
    pub async fn activate_fee_sponsor_init(
        &self,
        fee_sponsor_id: String,
    ) -> Result<crate::signer::UserActionChallenge, crate::error::Error> {
        let path = format!(
            "/fee-sponsors/{}/activate",
            urlencoding::encode(&fee_sponsor_id)
        );
        self.client
            .create_user_action_challenge(reqwest::Method::PUT, &path, None)
            .await
    }

    /// Finishes delegated signing for activateFeeSponsor: submits the signed challenge
    /// and issues the request.
    pub async fn activate_fee_sponsor_complete(
        &self,
        fee_sponsor_id: String,
        challenge_identifier: String,
        assertion: crate::signer::CredentialAssertion,
    ) -> Result<ActivateFeeSponsorResponse, crate::error::Error> {
        let path = format!(
            "/fee-sponsors/{}/activate",
            urlencoding::encode(&fee_sponsor_id)
        );
        let user_action = self
            .client
            .complete_user_action_signing(challenge_identifier, &assertion)
            .await?;
        self.client
            .request_with_user_action::<ActivateFeeSponsorResponse>(
                reqwest::Method::PUT,
                &path,
                None,
                &user_action,
            )
            .await
    }

    /// Retrieves all fees paid by the specific Fee Sponsor.
    pub async fn list_sponsored_fees(
        &self,
        fee_sponsor_id: String,
        query: Option<ListSponsoredFeesQuery>,
    ) -> Result<ListSponsoredFeesResponse, crate::error::Error> {
        let mut path = format!(
            "/fee-sponsors/{}/fees",
            urlencoding::encode(&fee_sponsor_id)
        );
        if let Some(query) = &query {
            let mut q: Vec<String> = Vec::new();
            if let Some(v) = &query.limit {
                q.push(format!("limit={}", urlencoding::encode(&v.to_string())));
            }
            if let Some(v) = &query.pagination_token {
                q.push(format!(
                    "paginationToken={}",
                    urlencoding::encode(&v.to_string())
                ));
            }
            if !q.is_empty() {
                path.push('?');
                path.push_str(&q.join("&"));
            }
        }
        self.client
            .request::<ListSponsoredFeesResponse>(reqwest::Method::GET, &path, None, false)
            .await
    }
}
