// Code generated by rust-sdk-generator. DO NOT EDIT.

#![allow(clippy::all)]

/// List Fee Sponsors
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListFeeSponsorsResponse {
    #[serde(rename = "items")]
    pub items: Vec<crate::types::FeeSponsor>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListFeeSponsorsQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListFeeSponsorsQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<i64>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
}

/// Create Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CreateFeeSponsorRequest {
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// Create Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CreateFeeSponsorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// Get Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GetFeeSponsorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// Delete Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeleteFeeSponsorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// Deactivate Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DeactivateFeeSponsorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// Activate Fee Sponsor
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ActivateFeeSponsorResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "walletId")]
    pub wallet_id: String,
    #[serde(rename = "network")]
    pub network: crate::types::Network,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "dateCreated")]
    pub date_created: String,
    #[serde(
        rename = "allowEndUser",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub allow_end_user: Option<bool>,
}

/// List Sponsored Fees
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListSponsoredFeesResponse {
    #[serde(rename = "items")]
    pub items: Vec<serde_json::Value>,
    #[serde(
        rename = "nextPageToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub next_page_token: Option<String>,
}

/// Query parameters for the ListSponsoredFeesQuery operation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ListSponsoredFeesQuery {
    #[serde(rename = "limit", default, skip_serializing_if = "Option::is_none")]
    pub limit: Option<String>,
    #[serde(
        rename = "paginationToken",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub pagination_token: Option<String>,
}
